import * as THREE from 'three';
import {disposeObject3D} from '@conduit/web3d/debug';
import type {FeatureTestContext,FeatureTestScene} from '../../FeatureTestScene';
import {generatePlanetDefinition,generatePlanetResourceProfile} from '@conduit/planet/generation';
import type {PlanetClass,PlanetDefinition} from '@conduit/planet/model';
import {Planet,createPlanetRenderProfile,getPlanetClassVisualProfile,OCEAN_COASTLINE_PROFILE,type PlanetRenderProfile,type SurfacePaletteKind} from '@conduit/planet/rendering';
import {getPlanetRadiusMeters} from '@conduit/planet/near-view';
import {PLANET_CLIMATE_DEBUG_MODES,createPlanetClimateDiagnostics,drawPlanetClimateDebugMap,type PlanetClimateDiagnostics} from '@conduit/planet/diagnostics';
import type {ClimateDebugMode} from '@conduit/planet/climate';
import {getPlanetScaleDiagnostics,getSystemPlanetRenderRadius} from '../../../spatial/SpatialRenderScale';
import {RegionalSurfacePatch} from './RegionalSurfacePatch';
const LAB_PLANET_RADIUS=3,SURFACE_TRANSITION_START_METERS=9_000_000,SURFACE_TRANSITION_END_METERS=500_000,REGIONAL_PATCH_FULL_METERS=8_700_000,ORBIT_HIDE_METERS=7_500_000,REGIONAL_PATCH_RELEASE_METERS=9_150_000,PURE_WORKER_CUBESPHERE_TEST=true,DEFAULT_ORBIT_LOD_CAP_LEVEL=6,ORBIT_LOD_CAP_ALTITUDE_RADIUS_MULTIPLIER=0.15;
const PLANET_CLASSES:PlanetClass[]=['barren','rocky','terrestrial','ocean','desert','ice','lava','toxic','carbon','metal_rich','gas_giant','ice_giant'];
type PlanetLayerToggles={surface:boolean;ocean:boolean;atmosphere:boolean;clouds:boolean;gasParticles:boolean;rings:boolean;moons:boolean;nearSurfaceTerrain:boolean;toxicHaze:boolean;};
export class PlanetLodTestScene implements FeatureTestScene{
readonly id='planet-lod';readonly name='Planet LOD';readonly category='Planets' as const;readonly description='Production Planet renderer with LOD stats.';private context:FeatureTestContext|null=null;private readonly root=new THREE.Group();private planet:Planet|null=null;private definition:PlanetDefinition|null=null;private profile:PlanetRenderProfile|null=null;private climateDiagnostics:PlanetClimateDiagnostics|null=null;private regionalPatch:RegionalSurfacePatch|null=null;private stats:HTMLElement|null=null;private climateCanvas:HTMLCanvasElement|null=null;private seed=3001;private planetClass:PlanetClass='ocean';private climateDebugMode:ClimateDebugMode='biome';private readonly layerToggles:PlanetLayerToggles={surface:true,ocean:true,atmosphere:true,clouds:true,gasParticles:true,rings:true,moons:true,nearSurfaceTerrain:true,toxicHaze:true};
init(c:FeatureTestContext){this.context=c;this.root.name='PlanetLodTestScene';c.scene.add(this.root);c.camera.position.set(0,3.2,9.5);c.controls.target.set(0,0,0);c.controls.enablePan=false;c.controls.update();this.createUi(c.uiRoot);this.createPlanet();}
update(dt:number){if(!this.context||!this.planet||!this.definition)return;const r=getPlanetRadiusMeters(this.definition),d=this.context.camera.position.length(),a=Math.max(0,(d/LAB_PLANET_RADIUS-1)*r),lodCapAltitude=r*ORBIT_LOD_CAP_ALTITUDE_RADIUS_MULTIPLIER,min=LAB_PLANET_RADIUS*(1+lodCapAltitude/r),lod=this.context.camera.position.clone();if(lod.length()<min)lod.setLength(min);if(PURE_WORKER_CUBESPHERE_TEST)this.disposeRegionalPatch();else this.updateRegionalPatch(a);this.planet.group.visible=true;this.planet.update(lod,dt);this.planet.setRenderQuality('idle');this.updateStats();}
dispose(){this.disposeRegionalPatch();this.planet?.dispose();this.planet=null;this.context?.scene.remove(this.root);disposeObject3D(this.root);this.root.clear();this.context=null;}
reset(){this.createPlanet();}
private updateRegionalPatch(a:number){if(!this.context||!this.definition||!this.profile)return;const enabled=this.layerToggles.nearSurfaceTerrain&&this.profile.rendererKind==='solid_surface';if(enabled&&!this.regionalPatch&&a<SURFACE_TRANSITION_START_METERS){this.regionalPatch=new RegionalSurfacePatch(this.definition,LAB_PLANET_RADIUS,this.context.camera.position);this.root.add(this.regionalPatch.group);}if(this.regionalPatch&&(!enabled||a>REGIONAL_PATCH_RELEASE_METERS)){this.disposeRegionalPatch();return;}if(this.regionalPatch)this.regionalPatch.update(this.context.camera.position,getRegionalPatchOpacity(a));}
private disposeRegionalPatch(){if(!this.regionalPatch)return;this.root.remove(this.regionalPatch.group);this.regionalPatch.dispose();this.regionalPatch=null;}
private createUi(root:HTMLElement){root.innerHTML=`<label style="display:block;margin:6px 0;">Class <select data-planet-class>${PLANET_CLASSES.map(p=>`<option value="${p}"${p===this.planetClass?' selected':''}>${formatPlanetClass(p)}</option>`).join('')}</select></label><label style="display:block;margin:6px 0;">Seed <input data-seed type="number" value="${this.seed}" style="width:110px;"></label><label style="display:block;margin:6px 0;">Climate Map <select data-climate-debug>${PLANET_CLIMATE_DEBUG_MODES.map(m=>`<option value="${m}"${m===this.climateDebugMode?' selected':''}>${formatDebugMode(m)}</option>`).join('')}</select></label><button data-apply-planet style="margin:4px;padding:6px 8px;">Apply</button><canvas data-climate-map width="240" height="120" style="display:block;width:240px;height:120px;margin-top:8px;border:1px solid rgba(120,180,255,.35);border-radius:4px;image-rendering:pixelated;background:#05070a;"></canvas><div data-planet-stats style="margin-top:8px;opacity:.78"></div>`;this.stats=root.querySelector('[data-planet-stats]');this.climateCanvas=root.querySelector('[data-climate-map]');root.querySelector<HTMLButtonElement>('[data-apply-planet]')?.addEventListener('click',()=>{const i=root.querySelector<HTMLInputElement>('[data-seed]'),s=root.querySelector<HTMLSelectElement>('[data-planet-class]'),n=Number(i?.value??this.seed);this.seed=Number.isFinite(n)?Math.max(1,Math.floor(n)):this.seed;this.planetClass=isPlanetClass(s?.value)?s.value:this.planetClass;this.createPlanet();});root.querySelector<HTMLSelectElement>('[data-climate-debug]')?.addEventListener('change',e=>{this.climateDebugMode=(e.currentTarget as HTMLSelectElement).value as ClimateDebugMode;this.updateClimateMap();});}
private createPlanet(){if(!this.context)return;this.disposeRegionalPatch();this.planet?.dispose();this.planet=null;this.definition=null;this.profile=null;this.climateDiagnostics=null;this.root.clear();this.context.clearReport();const g=generatePlanetDefinition(this.seed,{name:`LOD ${this.seed}`,semiMajorAxis:1,starIrradiance:1,forcePlanetClass:this.planetClass}),d=this.createDebugDefinition(g),p=this.createDebugRenderProfile(createPlanetRenderProfile(d));this.definition=d;this.profile=p;this.climateDiagnostics=createPlanetClimateDiagnostics(d);this.planet=new Planet(LAB_PLANET_RADIUS,this.context.rendererMode,null,{gasCloudParticles:this.layerToggles.gasParticles&&(d.class==='gas_giant'||d.class==='ice_giant'),moonSystem:this.layerToggles.moons,nearSurfaceTerrain:false},d,p);this.root.add(this.planet.group);this.context.report({status:'pass',label:'planet created',detail:`${d.class} / seed ${d.seed}`});this.updateClimateMap();}
private createDebugDefinition(d:PlanetDefinition):PlanetDefinition{if(this.layerToggles.ocean)return d;const x={...d,composition:{...d.composition,water:0},surface:{...d.surface,hasOcean:false,oceanLevel:-1},atmosphere:{...d.atmosphere,cloudCoverage:this.layerToggles.clouds?d.atmosphere.cloudCoverage:0}};return {...x,resources:generatePlanetResourceProfile({planetClass:x.class,composition:x.composition,atmosphere:x.atmosphere,surface:x.surface,climate:x.climate})};}
private createDebugRenderProfile(p:PlanetRenderProfile):PlanetRenderProfile{return {...p,enableOcean:p.enableOcean&&this.layerToggles.ocean,enableAtmosphere:p.enableAtmosphere&&this.layerToggles.atmosphere,enableClouds:p.enableClouds&&this.layerToggles.clouds,enableRings:p.enableRings&&this.layerToggles.rings};}
private updateStats(){if(!this.planet||!this.context||!this.stats||!this.definition||!this.profile)return;const t=this.planet.getTerrainStats(),v=getPlanetClassVisualProfile(this.profile.surfacePalette as SurfacePaletteKind),r=getPlanetRadiusMeters(this.definition),km=r/1000,gr=getSystemPlanetRenderRadius(r,this.definition.class),gs=getPlanetScaleDiagnostics(r,gr),d=this.context.camera.position.length(),a=Math.max(0,(d/LAB_PLANET_RADIUS-1)*r),tr=getSurfaceTransitionDebug(a),lodCapAltitude=r*ORBIT_LOD_CAP_ALTITUDE_RADIUS_MULTIPLIER,min=LAB_PLANET_RADIUS*(1+lodCapAltitude/r),cap=d<min,op=getRegionalPatchOpacity(a);this.stats.innerHTML=`class: ${this.planetClass}<br>renderer: ${this.context.rendererMode}<br>test mode: ${PURE_WORKER_CUBESPHERE_TEST?'WORKER CUBESPHERE ONLY':'regional transition'}<br>real radius: ${formatKilometers(km)} km<br>game radius: ${gr.toFixed(1)}u (${formatScaleMultiplier(gs.visualScaleMultiplier)})<br>visual profile: ${format01(v.ambientBoost)}<br>coast: ${formatRange(OCEAN_COASTLINE_PROFILE.waterHintStart,OCEAN_COASTLINE_PROFILE.waterHintEnd)}<br>patches: ${t.visibleMeshes}/${t.totalPatches}<br>max lod: ${t.maxLevel} / target cap ${DEFAULT_ORBIT_LOD_CAP_LEVEL}<br><br><b>surface transition debug</b><br>altitude: ${formatAltitude(a)}<br>phase: ${tr.phase}<br>blend: ${(tr.blend*100).toFixed(1)}%<br>orbit weight: ${(1-tr.blend).toFixed(2)} / surface weight: ${tr.blend.toFixed(2)}<br>thresholds: 9000 km → 500 km<br>worker LOD guard: ${cap?'ACTIVE':'off'} / ~level ${DEFAULT_ORBIT_LOD_CAP_LEVEL}<br>regional patch: ${this.regionalPatch?'ACTIVE':'DISABLED'} / opacity ${(op*100).toFixed(0)}%<br>regional fade: disabled for A/B test<br>renderer: worker CubeSphere visible`;}
private updateClimateMap(){if(this.climateCanvas&&this.definition)drawPlanetClimateDebugMap(this.climateCanvas,this.definition,this.climateDebugMode);}}
function getSurfaceTransitionDebug(a:number):{blend:number;phase:'orbit'|'transition'|'surface'}{const t=THREE.MathUtils.clamp((SURFACE_TRANSITION_START_METERS-a)/(SURFACE_TRANSITION_START_METERS-SURFACE_TRANSITION_END_METERS),0,1),b=t*t*(3-2*t);return{blend:b,phase:b<=0?'orbit':b>=1?'surface':'transition'};}
function getRegionalPatchOpacity(a:number){const t=THREE.MathUtils.clamp((SURFACE_TRANSITION_START_METERS-a)/(SURFACE_TRANSITION_START_METERS-REGIONAL_PATCH_FULL_METERS),0,1);return t*t*(3-2*t);}
function isPlanetClass(v:string|undefined):v is PlanetClass{return PLANET_CLASSES.includes(v as PlanetClass);}
function formatPlanetClass(v:PlanetClass){return v.split('_').map(p=>p.charAt(0).toUpperCase()+p.slice(1)).join(' ');}
function formatDebugMode(m:ClimateDebugMode){return m.replace(/([A-Z])/g,' $1').replace(/^./,f=>f.toUpperCase());}
function format01(v:number){return v.toFixed(2);}function formatRange(a:number,b:number){return `${a.toFixed(2)}-${b.toFixed(2)}`;}function formatKilometers(v:number){return Math.abs(v)>=100?v.toFixed(0):v.toFixed(1);}function formatScaleMultiplier(v:number){return v===0||!Number.isFinite(v)?'n/a':`${v.toFixed(4)}x`;}function formatAltitude(m:number){return m>=1_000_000?`${(m/1_000_000).toFixed(2)} Mm`:`${(m/1000).toFixed(1)} km`;}
